# Generated by Django 3.0.2 on 2020-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='exchangereferencerate',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
